baseURL = "/"
metaDataFormat = "yaml"
languageCode = "en-us"
title = "blogs"

[outputFormats.category]
baseName = "category"
mediatype = "application/json"

[outputs]
  page = ["json"]
  home = ["json"]
  section = ["json"]
  taxonomy = ["JSON"]
  taxonomyTerm = ["JSON"]

[taxonomies]
  category = "categories"

[permalinks]
  category = "/:section/:title"
  page = "/:section/:title"
