baseURL = "/"
ignoreErrors = ["error-output-taxonomy"]
metaDataFormat = "yaml"
languageCode = "en-us"
title = "blogs"

[outputFormats.category]
baseName = "category"
mediatype = "application/json"

[outputs]
  page = ["json"]
  home = ["json"]
  section = ["json"]
  taxonomy = ["json"]
  taxonomyTerm = ["json"]

[taxonomies]
  category = "category"

[permalinks]
  category = "/:section/:title"
  page = "/:section/:title"
